"""init

Revision ID: b6ffa9873793
Revises: 
Create Date: 2026-05-13 15:48:43.183647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6ffa9873793'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_phone_unique', 'users', ['phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_username_unique', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('discussions',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'starting', 'running', 'completed', 'error')", name='ck_discussions_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_discussions_user_created', 'discussions', ['owner_id', 'created_at'], unique=False)
    op.create_table('skills',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('generating', 'ready', 'error')", name='ck_skills_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skills_owner_created', 'skills', ['owner_id', 'created_at'], unique=False)
    op.create_index('idx_skills_owner_name_unique', 'skills', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_skills_public_created', 'skills', ['is_public', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_events',
    sa.Column('discussion_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ae_discussion_created', 'audit_events', ['discussion_id', 'created_at'], unique=False)
    op.create_index('idx_ae_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_table('discussion_agents',
    sa.Column('discussion_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_da_discussion', 'discussion_agents', ['discussion_id'], unique=False)
    op.create_index('idx_da_skill', 'discussion_agents', ['skill_id'], unique=False)
    op.create_table('discussion_messages',
    sa.Column('discussion_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("message_type IN ('host_intro', 'host_summary', 'agent_think', 'agent_speak', 'user_intervene')", name='ck_dm_message_type'),
    sa.ForeignKeyConstraint(['agent_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dm_discussion_round_created', 'discussion_messages', ['discussion_id', 'round_number', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dm_discussion_round_created', table_name='discussion_messages')
    op.drop_table('discussion_messages')
    op.drop_index('idx_da_skill', table_name='discussion_agents')
    op.drop_index('idx_da_discussion', table_name='discussion_agents')
    op.drop_table('discussion_agents')
    op.drop_index('idx_ae_user_created', table_name='audit_events')
    op.drop_index('idx_ae_discussion_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('idx_skills_public_created', table_name='skills', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_skills_owner_name_unique', table_name='skills', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_skills_owner_created', table_name='skills')
    op.drop_table('skills')
    op.drop_index('idx_discussions_user_created', table_name='discussions')
    op.drop_table('discussions')
    op.drop_index('idx_users_username_unique', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_phone_unique', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
